[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
colored = "2.1.0"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
syntect = "5.2.0"
